// ... existing code ...
public interface IDeviceService
{
    // ... existing code ...
    Task<bool> SetMouseRGBAsync(Device device, DeviceCommands.RGBEffectMode mode, byte red, byte green, byte blue, byte speed, byte brightness);
    // ... existing code ...
}